const wrestlerVariations = {
  "Hulk Hogan": ["Hulk Hogan", "Hulk Hogan/Hollywood Hogan", "Hollywood Hogan", "Hollywood Hulk Hogan"],
  "Steve Austin": ["Steve Austin", "Stone Cold Steve Austin", "Stunning Steve Austin"],
  "Scott Hall": ["Scott Hall", "Razor Ramon"],
  "Mick Foley": ["Mick Foley", "Mankind", "Cactus Jack", "Dude Love"],
  "Dean Ambrose": ["Dean Ambrose", "Jon Moxley"],
  "Big Show": ["Big Show", "The Giant"],
  "John Morrison": ["John Morrison", "Johnny Nitro/John Morrison", "Johnny Nitro", "Johnny Impact"],
  "Cesaro": ["Cesaro", "Antonio Cesaro"],
  "Goldust": ["Goldust", "Dustin Rhodes"],
  "Diesel": ["Diesel", "Kevin Nash"],
  "Rhino": ["Rhino", "Rhyno"],
  "Daniel Bryan": ["Daniel Bryan", "Bryan Danielson"],
  "Rusev": ["Rusev", "Miro"],
  "Andrade": ["Andrade", "Andrade Cien Almas"],
  "Big E": ["Big E", "Big E Langston"],
  "Dolph Ziggler": ["Dolph Ziggler", "Nic Nemeth"],
  "Drew Mcintyre": ["Drew Mcintyre", "Drew Galloway"],
  "Bobby Lashley": ["Bobby Lashley", "Lashley"],
  "Ultimate Warrior": ["Ultimate Warrior", "The Ultimate Warrior"],
  "Christian": ["Christian", "Christian Cage"],
  "Edge": ["Edge", "Adam Copeland"],
  "Undertaker": ["Undertaker", "The Undertaker"],
  "Finn Balor": ["Finn Balor", "Finn Bálor"],
  "Mr Perfect": ["Mr Perfect", "Curt Hennig"],
  "Charlotte Flair": ["Charlotte", "Charlotte Flair"],
  "John Cena": ["John Cena", "John Cena †"],
  "Dominik Mysterio": ["Dominik Mysterio †", "Dominik Mysterio"],
  "Hangman Adam Page": ["Hangman Adam Page †", "Hangman Adam Page"],
  "Solo Sikoa": ["Solo Sikoa †", "Solo Sikoa"],
  "Jd Mcdonagh": ["Jd Mcdonagh †", "Jd Mcdonagh"],
  "Oba Femi": ["Oba Femi †", "Oba Femi"],
  "Jacy Jayne": ["Jacy Jayne †", "Jacy Jayne"],
  "Alberto Del Rio": ["Alberto Del Rio", "Alberto El Patrón"],
  "Jack Swagger": ["Jack Swagger", "Jake Hager"],
  "Mr Mcmahon": ["Mr Mcmahon", "Mr. Mcmahon", "Vince Mcmahon"],
  "The Rock": ["The Rock", "Rocky Maivia", "Dwayne Johnson"],
  "Triple H": ["Triple H", "Hunter Hearst Helmsley", "The Game"],
  "Kane": ["Kane", "Glenn Jacobs"],
  "Rey Mysterio": ["Rey Mysterio", "Rey Mysterio Jr"],
  "Cm Punk": ["Cm Punk", "Phil Brooks"],
  "Kevin Owens": ["Kevin Owens", "Kevin Steen"],
  "Sami Zayn": ["Sami Zayn", "El Generico"],
  "Seth Rollins": ["Seth Rollins", "Tyler Black"],
  "Roman Reigns": ["Roman Reigns", "Joe Anoa'i"],
  "Cody Rhodes": ["Cody Rhodes", "Stardust"],
  "Randy Orton": ["Randy Orton", "The Viper"],
  "Bret Hart": ["Bret Hart", "The Hitman"],
  "Shawn Michaels": ["Shawn Michaels", "Hbk", "The Heartbreak Kid"],
  "Ric Flair": ["Ric Flair", "Nature Boy"],
  "Booker T": ["Booker T", "King Booker"],
  "Sting": ["Sting", "Steve Borden"],
  "Andre The Giant": ["Andre The Giant", "Andre Roussimoff"],
  "Mark Henry": ["Mark Henry", "World's Strongest Man"],
  "Batista": ["Batista", "Dave Batista"],
  "Goldberg": ["Goldberg", "Bill Goldberg"],
  "Aj Styles": ["Aj Styles", "Phenomenal One"]
};

export default wrestlerVariations;